# Welcome to Numpy 

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,44,3,4,])

In [3]:
myarr
#print(myarr)

array([ 3,  6, 44,  3,  4])

In [4]:
myarr=np.array([3,6,44,3,4,],np.int8)

In [5]:
myarr

array([ 3,  6, 44,  3,  4], dtype=int8)

In [6]:
print(myarr)

[ 3  6 44  3  4]


In [7]:
myarr[2]

np.int8(44)

In [8]:
print(myarr[2])

44


In [9]:
myarr2=np.array([[3,34,66,67,223,334,33]],np.int64)

In [10]:
myarr2

array([[  3,  34,  66,  67, 223, 334,  33]])

In [11]:
type(myarr2)

numpy.ndarray

In [12]:
myarr2.dtype

dtype('int64')

In [13]:
myarr2[0][3]

np.int64(67)

In [14]:
print(myarr2[0][3])

67


In [15]:
myarr2.dtype

dtype('int64')

In [16]:
myarr2[0,1]=1000

In [17]:
myarr2

array([[   3, 1000,   66,   67,  223,  334,   33]])

***Converting Python sequences to NumPy arrays***

In [18]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [30]:
a1D

array([1, 2, 3, 4])

In [31]:
a2D

array([[1, 2],
       [3, 4]])

In [32]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
a1d =np.array([1,2,3,4],np.int8)
a2d=np.array([[12,11,10],[1,2,3]],np.int32)
a3d=np.array([[[1,2,3,4],[4,3,2,1]],[[1,4,2,3],[2,3,4,5]]],np.int64)
print(a1d," \n")
print(a2d,"  \n")
print(a3d,"  \n")
print(a1d.dtype)
print(a2d.dtype)
print(a3d.dtype)

[1 2 3 4]  

[[12 11 10]
 [ 1  2  3]]   

[[[1 2 3 4]
  [4 3 2 1]]

 [[1 4 2 3]
  [2 3 4 5]]]   

int8
int32
int64


# Array Creation method 2 Conversion from other Python structures

In [52]:
listarr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], np.int64)

In [53]:
listarr.dtype

dtype('int64')

In [54]:
listarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
listarr[0][0][1]

np.int64(2)

In [55]:
listarr.shape

(4, 2)

In [56]:
listarr.size

8

In [59]:
dic=np.array({1,2,3})
print(dic)
dic.dtype
#problem is it will give object type

{1, 2, 3}


dtype('O')

# Intrinsic NumPy array creation functions (e.g. arange, ones, zeros)

In [61]:
zeroarr = np.zeros((2,4))

In [62]:
zeroarr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
zeroarr.dtype

dtype('float64')

In [64]:
zeroarr.size

8

In [65]:
zeroarr.shape

(2, 4)

**arange**

In [66]:
arr = np.arange(2,30)

In [68]:
arr
#it will give 1d array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**linspace**

In [72]:
arrlin=np.linspace(1,10,5)
                #( start , end , how many elements )
# it will give equally spaced 5 num

In [73]:
arrlin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**empty**

In [80]:
#it will give zero array
emp=np.empty((2,7))
            #(no of row , no of col)
#print(emp)

emp

**empty_like**

In [85]:
emp_lik=np.empty_like(arrlin)
emp_lik 
#use for manupulation

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**Identity matrix**

In [88]:
ide=np.identity(10)
ide
#it will give 10x10 identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [89]:
ide.shape

(10, 10)

**Reshape (reshape)**

In [91]:
arr= np.arange(99)

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [95]:
arr=arr.reshape(3,33)
#it will give 3 row and 33 each one row 
# but (2,33) not possible blc elemets is 99
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**Ravel (ravel)**

In [98]:
arr= arr.ravel()
arr
#it will covert in to normal 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis in array

In [100]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**SUM**

In [103]:
arr.sum(axis=0)
#it will add columns wise 1+4+7 , 2+5+8 ,... 

array([12, 15, 18])

In [106]:
#BUT
arr.sum(axis=1)
#add in rows wise

array([ 6, 15, 24])

**Transpose(T)**

In [110]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**.flat (Used for iteration in an array)**

In [111]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr.flat

In [113]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


**num of dimention**

In [115]:
arr.ndim
#for 2d

2

In [116]:
arr.size

9

In [118]:
arr.nbytes
#total bytes consumed\

72

**Max value index (.argmax)**

In [120]:
one=np.array([1,3,5,22,45,4444,99])
one

array([   1,    3,    5,   22,   45, 4444,   99])

In [122]:
one.argmax()
#index 5 

np.int64(5)

**.argsort()**

In [125]:
# sorted array index 
one.argsort()

array([0, 1, 2, 3, 4, 6, 5])

In [127]:
#for 2d array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [130]:
arr.argmin()
#it will give sortest number index value 
# 0th number index

np.int64(0)

In [132]:
arr.argmax()
#index 8 having maximum value 

np.int64(8)

In [135]:
arr.argmax(axis=1)

array([2, 2, 2])

In [136]:
arr.argmax(axis=0)

array([2, 2, 2])

In [139]:
arr.argsort(axis=1)
#in already in sorted manner 

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [140]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [141]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr.reshape(9,1)
# 9 rows and 1 columns 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Arithmatic operations 

In [144]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
arr2=np.array([[1, 4, 3],
       [2, 5, 7],
       [7, 11, 9]])

In [147]:
arr+arr2
#add two matrix or array 

array([[ 2,  6,  6],
       [ 6, 10, 13],
       [14, 19, 18]])

In [149]:
# but we can't do it in python 
[223,434]+[22,466]
#it will just concadinate the two list values 

[223, 434, 22, 466]

In [151]:
arr*arr2
#element wise multiplication 

array([[ 1,  8,  9],
       [ 8, 25, 42],
       [49, 88, 81]])

In [152]:
arr/arr2

array([[1.        , 0.5       , 1.        ],
       [2.        , 1.        , 0.85714286],
       [1.        , 0.72727273, 1.        ]])

In [154]:
arr%arr2 
#find out the modulo

array([[0, 2, 0],
       [0, 0, 6],
       [0, 8, 0]])

In [156]:
#square root of the elements present in an array 
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [157]:
arr.sum()

np.int64(45)

**Finding elements from the array (np.where())**

In [160]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
np.where(arr>7)
#index value (row,col)

(array([2, 2]), array([1, 2]))

In [165]:
type(np.where(arr>7))

tuple

**count zero and non zeros**

In [166]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
np.count_nonzero(arr)

9

In [169]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [171]:
#changes 
arr[1,1]=0
np.nonzero(arr)
#[1,1] has removed

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 2, 0, 1, 2]))

**Size compare**

In [172]:
import sys

In [177]:
np_arr=np.array(py_arr)

In [176]:
sys.getsizeof(1) * len(py_arr)
#one int size * length

112

In [179]:
np_arr.itemsize * np_arr.size
#size of one ele * size of arr(length)

32

**Array Convert list(.tolist)**

In [181]:
np_arr.tolist()

[2, 3, 45, 33]